### ISSUE TITLE
Peer To Peer Review - 11/12/2019

### ISSUE THREAD

**Issue by SofiBretz** [dev1980/facebook-clone#9]
## Enhancements:
- Replace find for find_by.
- Refactor the repeat code in the callback, on private on friendship controller.
- Remember to use the readme template, so your project can be more completed :)
- Here is the link of the template: `https://github.com/microverseinc/readme-template`
- Check the difference between using references and integer for the data type of the foreign keys.
## Further Comments:
- Clean project, good job! 

> Reviewed with :heart: by Team 35: The Deadpools

**Comment by mapra99** [comment]
Team, thanks for the suggestions made. In reply to them:

_Replace find for find_by._
**A:** In c996927 we replaced `find` for `find_by_id`. Thanks for that

_Refactor the repeat code in the callback, on private on friendship controller._
**A:** We discussed that, but for the moment we decided to not implement this. We'll take it in mind for future enhancements

_Remember to use the readme template, so your project can be more completed :)_
**A:** Done in 24b94f0 

_Check the difference between using references and integer for the data type of the foreign keys._
**A:** About that, @abdellani and I did the exercise of comparing the strategy of using `t.references` and we found that the result is the following:
1. It uses `bigint` data type for the foreign key, instead of `integer`.
2. It adds the `null: false` constraint to the foreign key
3. It creates the index for that column
4. It adds the `add_foreign_key` command to establish the relation between the tables.
![screenshot](https://i.imgur.com/AlIGJmp.png)
All these 4 things are positive to the database behavior, so yes, it is a good idea to use `t.references`. Thanks for that
